name: CI/CD Pipeline

on:
  push:
    branches: ["main"]  # Trigger on pushes to main (e.g., PR merges)
  pull_request:
    branches: ["main"]  # Trigger on PRs targeting main

jobs:
  pr-lint:
    name: pr-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only runs on PRs
    steps:
      - name: Lint PR Title & Commits
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          types: |
            fix
            feat
            chore
            docs
            style
            refactor
            test

  code-ql:
    if: github.event_name != 'push' || github.ref != 'refs/heads/main'  # Skip on PR merges
    uses: ./.github/workflows/codeql.yml  # Calls the code quality scan workflow
    with:
      github-token: ${{ github.token }}

  code-lint:
    if: github.event_name != 'push' || github.ref != 'refs/heads/main'  # Skip on PR merges
    uses: ./.github/workflows/code-lint.yml  # Calls the code linting workflow
    with:
      github-token: ${{ github.token }}
  pr-label:
    name: Label PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only runs on PRs
    steps:
      - name: Apply labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows/labeler.yml
