name: Lint Codebase

on: 
  workflow_call:
    inputs:
      github-token:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with :
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSX: true
          VALIDATE_TSX: true
