name: PR Lint

on:
  workflow_call:
    inputs:
      github-token:
        required: true
        type: string
jobs:
  pr-lint:
    name: Validate PR title and commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
