name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required for creating releases and updating tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  # Use the latest patch version of Node.js 18
          cache: npm
          cache-dependency-path: package-lock.json  # Cache tied to package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
